name: Latest blog post workflow

on:
  # This schedule runs the job every 12 hours
  schedule:
    - cron: '0 */12 * * *'
  # This allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    # This gives the action permission to write to your repo
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # Your feed URL is correct!
          feed_list: "https://medium.com/feed/@anirudhtrivedi3014"
